### PR TITLE
Moira client v0.1

### PR DESCRIPTION
**Pull request by Lookyan**
Moira client for API.

### CODE REVIEW

**Comment by gmlexx** [comment]
Hi @Lookyan!
It's seems a good stuff, but I'm not sure, that we can merge your PR in that way.
We already have .travis.yml and it should be merged with moira-client/.travis.yml if we wanted to have a single project.
Tests, setup.py, etc could be also merged, but may be it's more profitable to stay the client as a separate project if there is different python version support, like python 3, because your client doesn't rely on twisted framework.

**Comment by Lookyan** [comment]
Hi!
Yes, I think the same way, so can we create a new repo in moira-alert for moira client and put it there? I think it would be better that moira client will be a part of moira-alert ecosystem.

**Comment by marrrvin** [comment]
python-client is good name, I guess )

**Comment by Lookyan** [comment]
[python-moira-client](https://github.com/moira-alert/python-moira-client)

**Pull request closed without merging**
